using Continuum93.Emulator.Mnemonics;

namespace CompilerTests
{
    public class TestGenericInitializers
    {
        public static IEnumerable<object[]> AllGInitCases =>
        [
            ["LD r,n", "oooooooo uuuAAAAA BBBBBBBB"],
            ["LD r,r", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD r,(nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD r,(nnn,nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD r,(nnn,r)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD r,(nnn,rr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD r,(nnn,rrr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD r,(rrr)", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD r,(rrr,nnn)", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD r,(rrr,r)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD r,(rrr,rr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD r,(rrr,rrr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD r,fr", "oooooooo uuuAAAAA uuuuBBBB"],

            ["LD rr,nn", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB"],
            ["LD rr,r", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rr,rr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rr,(nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD rr,(nnn,nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rr,(nnn,r)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rr,(nnn,rr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rr,(nnn,rrr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rr,(rrr)", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rr,(rrr,nnn)", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rr,(rrr,r)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rr,(rrr,rr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rr,(rrr,rrr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rr,fr", "oooooooo uuuAAAAA uuuuBBBB"],

            ["LD rrr,nnn", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD rrr,r", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrr,rr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrr,rrr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrr,(nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD rrr,(nnn,nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rrr,(nnn,r)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrr,(nnn,rr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrr,(nnn,rrr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrr,(rrr)", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrr,(rrr,nnn)", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rrr,(rrr,r)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrr,(rrr,rr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrr,(rrr,rrr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrr,fr", "oooooooo uuuAAAAA uuuuBBBB"],

            ["LD rrrr,nnnn", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD rrrr,r", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrrr,rr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrrr,rrr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrrr,rrrr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrrr,(nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD rrrr,(nnn,nnn)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rrrr,(nnn,r)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrrr,(nnn,rr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrrr,(nnn,rrr)", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD rrrr,(rrr)", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD rrrr,(rrr,nnn)", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD rrrr,(rrr,r)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrrr,(rrr,rr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrrr,(rrr,rrr)", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD rrrr,fr", "oooooooo uuuAAAAA uuuuBBBB"],

            ["LD (nnn),nnnn,n", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC"],
            ["LD (nnn),nnnn,n,nnn", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD"],
            ["LD (nnn),r", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB"],
            ["LD (nnn),rr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB"],
            ["LD (nnn),rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB"],
            ["LD (nnn),rrrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB"],
            ["LD (nnn),(nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC uuuDDDDD"],
            ["LD (nnn),(nnn,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(nnn,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(nnn,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(nnn,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC uuuDDDDD"],
            ["LD (nnn),(rrr,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(rrr,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(rrr,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),(rrr,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn),fr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuuBBBB"],

            ["LD (nnn,nnn),nnnn,n", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (nnn,nnn),nnnn,n,nnn", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (nnn,nnn),r", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (nnn,nnn),rr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (nnn,nnn),rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (nnn,nnn),rrrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (nnn,nnn),(nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,nnn),(nnn,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(nnn,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(nnn,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(nnn,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,nnn),(rrr,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(rrr,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(rrr,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),(rrr,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,nnn),fr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuuCCCC"],

            ["LD (nnn,r),nnnn,n", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (nnn,r),nnnn,n,nnn", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (nnn,r),r", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,r),rr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,r),rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,r),rrrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,r),(nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,r),(nnn,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(nnn,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(nnn,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(nnn,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,r),(rrr,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(rrr,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(rrr,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),(rrr,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,r),fr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuuCCCC"],

            ["LD (nnn,rr),nnnn,n", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (nnn,rr),nnnn,n,nnn", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (nnn,rr),r", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rr),rr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rr),rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rr),rrrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rr),(nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,rr),(nnn,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(nnn,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(nnn,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(nnn,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,rr),(rrr,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(rrr,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(rrr,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),(rrr,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rr),fr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuuCCCC"],

            ["LD (nnn,rrr),nnnn,n", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (nnn,rrr),nnnn,n,nnn", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (nnn,rrr),r", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rrr),rr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rrr),rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rrr),rrrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (nnn,rrr),(nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,rrr),(nnn,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(nnn,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(nnn,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(nnn,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (nnn,rrr),(rrr,nnn),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(rrr,r),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(rrr,rr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),(rrr,rrr),n,rrr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (nnn,rrr),fr", "oooooooo AAAAAAAA AAAAAAAA AAAAAAAA uuuBBBBB uuuuCCCC"],

            ["LD (rrr),nnnn,n", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC"],
            ["LD (rrr),nnnn,n,nnn", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD"],
            ["LD (rrr),r", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD (rrr),rr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD (rrr),rrr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD (rrr),rrrr", "oooooooo uuuAAAAA uuuBBBBB"],
            ["LD (rrr),(nnn),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC uuuDDDDD"],
            ["LD (rrr),(nnn,nnn),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(nnn,r),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(nnn,rr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(nnn,rrr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC uuuDDDDD"],
            ["LD (rrr),(rrr,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(rrr,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(rrr,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),(rrr,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr),fr", "oooooooo uuuAAAAA uuuuBBBB"],

            ["LD (rrr,nnn),nnnn,n", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (rrr,nnn),nnnn,n,nnn", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (rrr,nnn),r", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (rrr,nnn),rr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (rrr,nnn),rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (rrr,nnn),rrrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD (rrr,nnn),(nnn),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,nnn),(nnn,nnn),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(nnn,r),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(nnn,rr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(nnn,rrr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(rrr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,nnn),(rrr,nnn),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(rrr,r),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(rrr,rr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),(rrr,rrr),n,rrr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,nnn),fr", "oooooooo uuuAAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuuCCCC"],

            ["LD (rrr,r),nnnn,n", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (rrr,r),nnnn,n,nnn", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (rrr,r),r", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,r),rr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,r),rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,r),rrrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,r),(nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,r),(nnn,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(nnn,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(nnn,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(nnn,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,r),(rrr,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(rrr,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(rrr,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),(rrr,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,r),fr", "oooooooo uuuAAAAA uuuBBBBB uuuuCCCC"],

            ["LD (rrr,rr),nnnn,n", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (rrr,rr),nnnn,n,nnn", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (rrr,rr),r", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rr),rr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rr),rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rr),rrrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rr),(nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,rr),(nnn,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(nnn,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(nnn,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(nnn,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,rr),(rrr,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(rrr,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(rrr,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),(rrr,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rr),fr", "oooooooo uuuAAAAA uuuBBBBB uuuuCCCC"],

            ["LD (rrr,rrr),nnnn,n", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD"],
            ["LD (rrr,rrr),nnnn,n,nnn", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD EEEEEEEE EEEEEEEE EEEEEEEE"],
            ["LD (rrr,rrr),r", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rrr),rr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rrr),rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rrr),rrrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC"],
            ["LD (rrr,rrr),(nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,rrr),(nnn,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(nnn,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(nnn,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(nnn,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD uuuEEEEE"],
            ["LD (rrr,rrr),(rrr,nnn),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC DDDDDDDD DDDDDDDD DDDDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(rrr,r),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(rrr,rr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),(rrr,rrr),n,rrr", "oooooooo uuuAAAAA uuuBBBBB uuuCCCCC uuuDDDDD EEEEEEEE uuuFFFFF"],
            ["LD (rrr,rrr),fr", "oooooooo uuuAAAAA uuuBBBBB uuuuCCCC"],

            ["LD fr,nnnn", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD fr,r", "oooooooo uuuuAAAA uuuBBBBB"],
            ["LD fr,rr", "oooooooo uuuuAAAA uuuBBBBB"],
            ["LD fr,rrr", "oooooooo uuuuAAAA uuuBBBBB"],
            ["LD fr,rrrr", "oooooooo uuuuAAAA uuuBBBBB"],
            ["LD fr,(nnn)", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB"],
            ["LD fr,(nnn,nnn)", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD fr,(nnn,r)", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD fr,(nnn,rr)", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD fr,(nnn,rrr)", "oooooooo uuuuAAAA BBBBBBBB BBBBBBBB BBBBBBBB uuuCCCCC"],
            ["LD fr,(rrr)", "oooooooo uuuuAAAA uuuBBBBB"],
            ["LD fr,(rrr,nnn)", "oooooooo uuuuAAAA uuuBBBBB CCCCCCCC CCCCCCCC CCCCCCCC"],
            ["LD fr,(rrr,r)", "oooooooo uuuuAAAA uuuBBBBB uuuCCCCC"],
            ["LD fr,(rrr,rr)", "oooooooo uuuuAAAA uuuBBBBB uuuCCCCC"],
            ["LD fr,(rrr,rrr)", "oooooooo uuuuAAAA uuuBBBBB uuuCCCCC"],
            ["LD fr,fr", "oooooooo uuuuAAAA uuuuBBBB"],
        ];

        [Theory]
        [MemberData(nameof(AllGInitCases))]
        public void TestGInit(string inst, string expBits)
        {
            var op = Mnem.OPS[inst];
            Assert.Equal(expBits, op.Format);
        }
    }
}
